#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────
# sync.sh — Skill Library Sync (Bash / Git Bash / WSL)
#
# Usage:
#   ./sync.sh push [codex|claude|factory|desktop|all]
#   ./sync.sh pull [codex|claude|factory|all]
#   ./sync.sh status
#   ./sync.sh diff [codex|claude|factory|desktop|all]
# ─────────────────────────────────────────────────────────────
set -euo pipefail

LIBRARY_DIR="$HOME/skill-library"
CODEX_DIR="$HOME/.codex/skills"
CLAUDE_DIR="$HOME/.claude/commands"
FACTORY_DIR="$HOME/.factory/droids"
# Claude desktop app (Cowork) skills. The GUID segments are tied to the current
# app install; if push reports the dir missing, locate the new path and update
# this line (see the matching comment in sync.ps1). Library -> desktop is ONE-WAY.
DESKTOP_DIR="${APPDATA:-$HOME/AppData/Roaming}/Claude/local-agent-mode-sessions/skills-plugin/c6f03819-82ac-4592-af90-11a16ffe8d62/86adc332-a4c3-440b-9c09-a8f0d4221001/skills"
AUTOGEN_MARKER="<!-- AUTO-GENERATED from skill-library. Do not edit directly. -->"

# Colors
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[0;33m'
CYAN='\033[0;36m'; GRAY='\033[0;90m'; NC='\033[0m'

# ── Helpers ──────────────────────────────────────────────────

read_catalog_field() {
    local file="$1" field="$2"
    grep -E "^\s*${field}:" "$file" 2>/dev/null | head -1 | sed "s/^[^:]*:\s*//" | tr -d '"'
}

read_catalog_target() {
    local file="$1" target="$2"
    # Look for target under "targets:" block
    awk "/^targets:/{found=1; next} found && /^\s+${target}:/{print \$2; exit} found && /^[^ ]/{exit}" "$file" 2>/dev/null
}

get_skillmd_body() {
    local file="$1"
    # Strip YAML frontmatter (between --- markers)
    awk 'BEGIN{fm=0} /^---$/{fm++; next} fm>=2{print}' "$file"
}

is_autogenerated() {
    local file="$1"
    # Marker is on line 1 (Factory/legacy) or just below the frontmatter (Claude commands)
    [[ -f "$file" ]] && head -30 "$file" | grep -qF "AUTO-GENERATED from skill-library"
}

get_skillmd_frontmatter() {
    local file="$1"
    # Print frontmatter including both --- fences; prints nothing if the file has none
    head -1 "$file" | grep -q '^---$' || return 0
    awk '/^---$/{p++; print; if(p==2) exit; next} {print}' "$file"
}

is_junction_or_symlink() {
    [[ -L "$1" ]] || [[ -d "$1" && "$(stat -c '%F' "$1" 2>/dev/null || file "$1")" == *"symbolic"* ]]
}

# ── Catalog JSON ─────────────────────────────────────────────

update_catalog_json() {
    local outfile="$LIBRARY_DIR/catalog.json"
    local total=0 codex_count=0 claude_count=0 factory_count=0
    local skill_count=0 command_count=0 droid_count=0
    local skills_json="["
    local first=true

    for dir in "$LIBRARY_DIR"/*/; do
        [[ -d "$dir" ]] || continue
        local name=$(basename "$dir")
        local skill_md="$dir/SKILL.md"
        local catalog_yaml="$dir/catalog.yaml"
        [[ -f "$skill_md" ]] || continue

        local origin=$(read_catalog_field "$catalog_yaml" "origin")
        local kind=$(read_catalog_field "$catalog_yaml" "kind")
        local tags=$(read_catalog_field "$catalog_yaml" "tags")
        local codex_t=$(read_catalog_target "$catalog_yaml" "codex")
        local claude_t=$(read_catalog_target "$catalog_yaml" "claude")
        local factory_t=$(read_catalog_target "$catalog_yaml" "factory")

        # Extract description (handles >- multi-line scalars)
        local desc=""
        local in_fm=$(awk 'BEGIN{p=0} /^---$/{p++; next} p==1{print} p>=2{exit}' "$skill_md")
        local desc_line=$(echo "$in_fm" | grep -n '^description:' | head -1)
        if [[ -n "$desc_line" ]]; then
            local desc_num=${desc_line%%:*}
            local desc_val=$(echo "$desc_line" | sed 's/^[0-9]*:description:\s*//')
            if echo "$desc_val" | grep -qE '^[>|]-?\s*$'; then
                # Multi-line scalar: collect indented continuation lines
                desc=$(echo "$in_fm" | tail -n +$((desc_num + 1)) | awk '/^[[:space:]]+/{gsub(/^[[:space:]]+/,""); printf "%s ", $0; next} {exit}' | sed 's/ $//')
            elif echo "$desc_val" | grep -qE '^".*"$'; then
                desc=$(echo "$desc_val" | sed 's/^"//' | sed 's/"$//')
            else
                desc=$(echo "$desc_val" | tr -d '"')
            fi
        fi
        desc=$(echo "$desc" | head -c 200)

        local has_scripts=$([[ -d "${dir}scripts" ]] && echo "true" || echo "false")
        local has_refs=$([[ -d "${dir}references" ]] && echo "true" || echo "false")
        local has_assets=$([[ -d "${dir}assets" ]] && echo "true" || echo "false")

        [[ "$first" == "true" ]] && first=false || skills_json+=","
        # Escape backslashes then quotes for valid JSON
        local desc_escaped=$(echo "$desc" | sed 's/\\/\\\\/g' | sed 's/"/\\"/g')
        skills_json+=$(printf '\n    {"id":"%s","description":"%s","origin":"%s","kind":"%s","hasScripts":%s,"hasReferences":%s,"hasAssets":%s,"path":"%s/"}' \
            "$name" "$desc_escaped" "$origin" "$kind" "$has_scripts" "$has_refs" "$has_assets" "$name")

        total=$((total + 1))
        case "$origin" in
            codex) codex_count=$((codex_count + 1)) ;;
            claude) claude_count=$((claude_count + 1)) ;;
            factory) factory_count=$((factory_count + 1)) ;;
        esac
        case "$kind" in
            skill) skill_count=$((skill_count + 1)) ;;
            command) command_count=$((command_count + 1)) ;;
            droid) droid_count=$((droid_count + 1)) ;;
        esac
    done

    skills_json+="]"

    cat > "$outfile" << EOF
{
  "version": 1,
  "generated": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "skills": $skills_json,
  "stats": {
    "total": $total,
    "byOrigin": {"codex": $codex_count, "claude": $claude_count, "factory": $factory_count},
    "byKind": {"skill": $skill_count, "command": $command_count, "droid": $droid_count}
  }
}
EOF
    echo -e "  ${CYAN}Updated catalog.json ($total skills)${NC}"
}

# ── Push ─────────────────────────────────────────────────────

push_codex() {
    echo -e "\n${YELLOW}[Codex] Syncing via directory junctions/symlinks...${NC}"
    local count=0
    for dir in "$LIBRARY_DIR"/*/; do
        [[ -d "$dir" ]] || continue
        local name=$(basename "$dir")
        # Skip backup artifacts left behind by previous push runs
        [[ "$name" == *.bak || "$name" == *.bak.* ]] && continue
        local catalog_yaml="$dir/catalog.yaml"
        local target_codex=$(read_catalog_target "$catalog_yaml" "codex")
        [[ "$target_codex" == "true" ]] || continue

        local dest="$CODEX_DIR/$name"

        if [[ -L "$dest" ]] || powershell.exe -NoProfile -Command "(Get-Item '$dest' -Force -ErrorAction SilentlyContinue).Attributes -band [System.IO.FileAttributes]::ReparsePoint" 2>/dev/null | grep -qi "true"; then
            echo -e "  ${GRAY}[OK] $name — link exists${NC}"
            count=$((count + 1))
            continue
        fi

        if [[ -d "$dest" ]]; then
            echo -e "  ${YELLOW}[BACKUP] $name — backing up original${NC}"
            mv "$dest" "${dest}.bak"
        fi

        # Create junction on Windows via PowerShell (more reliable than cmd from Git Bash)
        local win_dest=$(cygpath -w "$dest" 2>/dev/null || echo "$dest")
        local win_src=$(cygpath -w "${dir%/}" 2>/dev/null || echo "${dir%/}")
        powershell.exe -NoProfile -Command "cmd /c 'mklink /J \"$win_dest\" \"$win_src\"'" > /dev/null 2>&1 && {
            echo -e "  ${GREEN}[NEW] $name — junction created${NC}"
        } || {
            # Fallback: create symlink (may need admin)
            ln -s "$dir" "$dest" 2>/dev/null && {
                echo -e "  ${GREEN}[NEW] $name — symlink created${NC}"
            } || {
                echo -e "  ${RED}[FAIL] $name — could not create link (try running as admin)${NC}"
            }
        }
        count=$((count + 1))
    done
    echo -e "  ${CYAN}Codex: $count skills synced${NC}"
}

push_claude() {
    echo -e "\n${YELLOW}[Claude] Generating command files...${NC}"
    local count=0
    for dir in "$LIBRARY_DIR"/*/; do
        [[ -d "$dir" ]] || continue
        local name=$(basename "$dir")
        local catalog_yaml="$dir/catalog.yaml"
        local target_claude=$(read_catalog_target "$catalog_yaml" "claude")
        [[ "$target_claude" == "true" ]] || continue

        local skill_md="$dir/SKILL.md"
        [[ -f "$skill_md" ]] || continue

        local dest="$CLAUDE_DIR/$name.md"
        local body=$(get_skillmd_body "$skill_md")
        local fm=$(get_skillmd_frontmatter "$skill_md")

        # Frontmatter must stay at line 1 so Claude Code surfaces the description;
        # the auto-gen marker goes between frontmatter and body.
        if [[ -n "$fm" ]]; then
            printf '%s\n%s\n\n%s' "$fm" "$AUTOGEN_MARKER" "$body" > "$dest"
        else
            printf '%s\n\n%s' "$AUTOGEN_MARKER" "$body" > "$dest"
        fi
        echo -e "  ${GREEN}[GEN] $name.md${NC}"
        count=$((count + 1))
    done
    echo -e "  ${CYAN}Claude: $count commands synced${NC}"
}

push_factory() {
    echo -e "\n${YELLOW}[Factory] Generating droid files...${NC}"
    local count=0
    for dir in "$LIBRARY_DIR"/*/; do
        [[ -d "$dir" ]] || continue
        local name=$(basename "$dir")
        local catalog_yaml="$dir/catalog.yaml"
        local target_factory=$(read_catalog_target "$catalog_yaml" "factory")
        [[ "$target_factory" == "true" ]] || continue

        local skill_md="$dir/SKILL.md"
        [[ -f "$skill_md" ]] || continue

        local dest="$FACTORY_DIR/$name.md"
        # Factory needs full content including frontmatter
        printf '%s\n' "$AUTOGEN_MARKER" > "$dest"
        cat "$skill_md" >> "$dest"
        echo -e "  ${GREEN}[GEN] $name.md${NC}"
        count=$((count + 1))
    done
    echo -e "  ${CYAN}Factory: $count droids synced${NC}"
}

push_desktop() {
    echo -e "\n${YELLOW}[Desktop] Copying skill directories to Claude desktop app...${NC}"
    if [[ ! -d "$DESKTOP_DIR" ]]; then
        echo -e "  ${YELLOW}[SKIP] Desktop skills dir not found: $DESKTOP_DIR${NC}"
        echo -e "  ${YELLOW}The app install GUIDs may have changed; see the comment above DESKTOP_DIR.${NC}"
        return 0
    fi
    local count=0
    for dir in "$LIBRARY_DIR"/*/; do
        [[ -d "$dir" ]] || continue
        local name=$(basename "$dir")
        [[ "$name" == *.bak* ]] && continue
        local catalog_yaml="$dir/catalog.yaml"
        local target_desktop=$(read_catalog_target "$catalog_yaml" "desktop")
        [[ "$target_desktop" == "true" ]] || continue
        [[ -f "$dir/SKILL.md" ]] || continue

        # Mirror the skill directory, minus library-only metadata. Only
        # desktop-targeted skills are touched; app-managed stock skills are not.
        local dest="$DESKTOP_DIR/$name"
        rm -rf "$dest"
        mkdir -p "$dest"
        (cd "$dir" && find . -mindepth 1 -maxdepth 1 ! -name catalog.yaml -exec cp -r {} "$dest/" \;)
        echo -e "  ${GREEN}[GEN] $name/${NC}"
        count=$((count + 1))
    done
    echo -e "  ${CYAN}Desktop: $count skills synced${NC}"
}

# ── Pull ─────────────────────────────────────────────────────

pull_codex() {
    echo -e "\n${YELLOW}[Codex] Scanning for new skills...${NC}"
    local imported=0
    for dir in "$CODEX_DIR"/*/; do
        [[ -d "$dir" ]] || continue
        local name=$(basename "$dir")
        [[ "$name" == ".system" ]] && continue
        [[ -L "$dir" ]] && continue
        # Skip backup artifacts produced by push (prevents .bak.bak.bak loop)
        [[ "$name" == *.bak || "$name" == *.bak.* ]] && continue

        local lib_dest="$LIBRARY_DIR/$name"
        [[ -d "$lib_dest" ]] && continue

        echo -e "  ${GREEN}[IMPORT] $name — new Codex skill${NC}"
        cp -r "$dir" "$lib_dest"
        cat > "$lib_dest/catalog.yaml" << EOF
id: $name
origin: codex
kind: skill
tags: []
targets:
  codex: true
  claude: false
  factory: false
EOF
        imported=$((imported + 1))
    done
    echo -e "  ${CYAN}Codex: $imported new skills imported${NC}"
}

pull_claude() {
    echo -e "\n${YELLOW}[Claude] Scanning for new/updated commands...${NC}"
    local imported=0
    local updated=0
    for file in "$CLAUDE_DIR"/*.md; do
        [[ -f "$file" ]] || continue
        is_autogenerated "$file" && continue

        local name=$(basename "$file" .md)
        local lib_dest="$LIBRARY_DIR/$name"
        if [[ -d "$lib_dest" ]]; then
            # Existing skill — check if Claude version has diverged
            local lib_skill="$lib_dest/SKILL.md"
            if [[ -f "$lib_skill" ]]; then
                local lib_body=$(get_skillmd_body "$lib_skill")
                local claude_body=$(cat "$file")
                if ! diff -q <(echo "$lib_body") <(echo "$claude_body") &>/dev/null; then
                    echo -e "  ${YELLOW}[UPDATE] $name — Claude version differs, updating library${NC}"
                    # Preserve frontmatter, replace body
                    local frontmatter=$(awk 'BEGIN{p=0} /^---$/{p++; if(p==2){print; exit}} {print}' "$lib_skill")
                    printf '%s\n%s' "$frontmatter" "$claude_body" > "$lib_skill"
                    updated=$((updated + 1))
                fi
            fi
            continue
        fi

        echo -e "  ${GREEN}[IMPORT] $name — new Claude command${NC}"
        mkdir -p "$lib_dest"
        local first_line=$(head -1 "$file" | head -c 120)
        cat > "$lib_dest/SKILL.md" << EOF
---
name: "$name"
description: "$first_line"
---
$(cat "$file")
EOF
        cat > "$lib_dest/catalog.yaml" << EOF
id: $name
origin: claude
kind: command
tags: []
targets:
  codex: false
  claude: true
  factory: false
EOF
        imported=$((imported + 1))
    done
    echo -e "  ${CYAN}Claude: $imported new, $updated updated${NC}"
}

pull_factory() {
    echo -e "\n${YELLOW}[Factory] Scanning for new/updated droids...${NC}"
    local imported=0
    local updated=0
    for file in "$FACTORY_DIR"/*.md; do
        [[ -f "$file" ]] || continue
        is_autogenerated "$file" && continue

        local name=$(basename "$file" .md)
        local lib_dest="$LIBRARY_DIR/$name"
        if [[ -d "$lib_dest" ]]; then
            # Existing skill — check if Factory version has diverged
            local lib_skill="$lib_dest/SKILL.md"
            if [[ -f "$lib_skill" ]]; then
                local lib_full=$(cat "$lib_skill")
                local factory_full=$(cat "$file")
                if ! diff -q <(echo "$lib_full") <(echo "$factory_full") &>/dev/null; then
                    echo -e "  ${YELLOW}[UPDATE] $name — Factory version differs, updating library${NC}"
                    cp "$file" "$lib_skill"
                    updated=$((updated + 1))
                fi
            fi
            continue
        fi

        echo -e "  ${GREEN}[IMPORT] $name — new Factory droid${NC}"
        mkdir -p "$lib_dest"
        cp "$file" "$lib_dest/SKILL.md"
        cat > "$lib_dest/catalog.yaml" << EOF
id: $name
origin: factory
kind: droid
tags: []
targets:
  codex: false
  claude: false
  factory: true
EOF
        imported=$((imported + 1))
    done
    echo -e "  ${CYAN}Factory: $imported new, $updated updated${NC}"
}

# ── Diff ─────────────────────────────────────────────────────

diff_codex() {
    echo -e "\n${YELLOW}[Codex] Checking for content differences...${NC}"
    local diffs=0
    for dir in "$LIBRARY_DIR"/*/; do
        [[ -d "$dir" ]] || continue
        local name=$(basename "$dir")
        local catalog_yaml="$dir/catalog.yaml"
        local target_codex=$(read_catalog_target "$catalog_yaml" "codex")
        [[ "$target_codex" == "true" ]] || continue

        local dest="$CODEX_DIR/$name"
        if [[ ! -d "$dest" ]]; then
            echo -e "  ${RED}[MISSING] $name — not in Codex dir${NC}"
            diffs=$((diffs + 1))
            continue
        fi
        if [[ -L "$dest" ]]; then
            # Symlink — content should be identical
            continue
        fi
        # Check for NTFS junction via PowerShell if available
        if command -v powershell.exe &>/dev/null; then
            local is_junction=$(powershell.exe -NoProfile -Command "(Get-Item '$(cygpath -w "$dest" 2>/dev/null || echo "$dest")' -Force -ErrorAction SilentlyContinue).Attributes -band [System.IO.FileAttributes]::ReparsePoint" 2>/dev/null)
            if echo "$is_junction" | grep -qi "true"; then
                continue
            fi
        fi
        # Regular directory — diff SKILL.md
        if [[ -f "$dir/SKILL.md" && -f "$dest/SKILL.md" ]]; then
            local changes=$(diff --brief "$dir/SKILL.md" "$dest/SKILL.md" 2>/dev/null)
            if [[ -n "$changes" ]]; then
                echo -e "  ${RED}[CHANGED] $name — SKILL.md differs (not a junction)${NC}"
                diff -u "$dir/SKILL.md" "$dest/SKILL.md" 2>/dev/null | head -20 | sed 's/^/    /'
                diffs=$((diffs + 1))
            fi
        fi
    done
    if [[ $diffs -eq 0 ]]; then
        echo -e "  ${GREEN}No differences found${NC}"
    else
        echo -e "  ${RED}$diffs skill(s) with differences${NC}"
    fi
}

diff_claude() {
    echo -e "\n${YELLOW}[Claude] Checking for content differences...${NC}"
    local diffs=0
    for dir in "$LIBRARY_DIR"/*/; do
        [[ -d "$dir" ]] || continue
        local name=$(basename "$dir")
        local catalog_yaml="$dir/catalog.yaml"
        local target_claude=$(read_catalog_target "$catalog_yaml" "claude")
        [[ "$target_claude" == "true" ]] || continue

        local skill_md="$dir/SKILL.md"
        [[ -f "$skill_md" ]] || continue

        local dest="$CLAUDE_DIR/$name.md"
        if [[ ! -f "$dest" ]]; then
            echo -e "  ${RED}[MISSING] $name.md — not in Claude dir${NC}"
            diffs=$((diffs + 1))
            continue
        fi

        # Compare library body vs deployed (strip frontmatter and auto-gen marker)
        local lib_body=$(get_skillmd_body "$skill_md")
        local deployed_body
        if head -1 "$dest" | grep -q '^---$'; then
            deployed_body=$(get_skillmd_body "$dest" | sed '/AUTO-GENERATED from skill-library/d' | sed '/^$/N;/^\n$/d')
        else
            deployed_body=$(sed '1{/AUTO-GENERATED from skill-library/d;}' "$dest" | sed '/^$/N;/^\n$/d')
        fi

        if ! diff -q <(echo "$lib_body") <(echo "$deployed_body") &>/dev/null; then
            echo -e "  ${RED}[CHANGED] $name.md${NC}"
            diff -u <(echo "$lib_body") <(echo "$deployed_body") 2>/dev/null | head -15 | sed 's/^/    /'
            diffs=$((diffs + 1))
        fi
    done

    # Unmanaged files
    for file in "$CLAUDE_DIR"/*.md; do
        [[ -f "$file" ]] || continue
        is_autogenerated "$file" && continue
        local name=$(basename "$file" .md)
        [[ -d "$LIBRARY_DIR/$name" ]] && continue
        echo -e "  ${YELLOW}[UNTRACKED] $(basename "$file") — exists in Claude but not in library${NC}"
        diffs=$((diffs + 1))
    done

    if [[ $diffs -eq 0 ]]; then
        echo -e "  ${GREEN}No differences found${NC}"
    else
        echo -e "  ${RED}$diffs item(s) with differences${NC}"
    fi
}

diff_factory() {
    echo -e "\n${YELLOW}[Factory] Checking for content differences...${NC}"
    local diffs=0
    for dir in "$LIBRARY_DIR"/*/; do
        [[ -d "$dir" ]] || continue
        local name=$(basename "$dir")
        local catalog_yaml="$dir/catalog.yaml"
        local target_factory=$(read_catalog_target "$catalog_yaml" "factory")
        [[ "$target_factory" == "true" ]] || continue

        local skill_md="$dir/SKILL.md"
        [[ -f "$skill_md" ]] || continue

        local dest="$FACTORY_DIR/$name.md"
        if [[ ! -f "$dest" ]]; then
            echo -e "  ${RED}[MISSING] $name.md — not in Factory dir${NC}"
            diffs=$((diffs + 1))
            continue
        fi

        # Compare library full content vs deployed (strip auto-gen marker)
        local lib_full=$(cat "$skill_md")
        local deployed_body=$(sed '1{/AUTO-GENERATED from skill-library/d;}' "$dest" | sed '/^$/N;/^\n$/d')

        if ! diff -q <(echo "$lib_full") <(echo "$deployed_body") &>/dev/null; then
            local lib_len=${#lib_full}
            local dep_len=${#deployed_body}
            echo -e "  ${RED}[CHANGED] $name.md (library: ${lib_len} chars, factory: ${dep_len} chars)${NC}"
            diff -u <(echo "$lib_full") <(echo "$deployed_body") 2>/dev/null | head -15 | sed 's/^/    /'
            diffs=$((diffs + 1))
        fi
    done

    # Unmanaged files
    for file in "$FACTORY_DIR"/*.md; do
        [[ -f "$file" ]] || continue
        is_autogenerated "$file" && continue
        local name=$(basename "$file" .md)
        [[ -d "$LIBRARY_DIR/$name" ]] && continue
        echo -e "  ${YELLOW}[UNTRACKED] $(basename "$file") — exists in Factory but not in library${NC}"
        diffs=$((diffs + 1))
    done

    if [[ $diffs -eq 0 ]]; then
        echo -e "  ${GREEN}No differences found${NC}"
    else
        echo -e "  ${RED}$diffs item(s) with differences${NC}"
    fi
}

diff_desktop() {
    echo -e "\n${YELLOW}[Desktop] Checking for content differences...${NC}"
    if [[ ! -d "$DESKTOP_DIR" ]]; then
        echo -e "  ${YELLOW}[SKIP] Desktop skills dir not found: $DESKTOP_DIR${NC}"
        return 0
    fi
    local diffs=0
    for dir in "$LIBRARY_DIR"/*/; do
        [[ -d "$dir" ]] || continue
        local name=$(basename "$dir")
        local catalog_yaml="$dir/catalog.yaml"
        local target_desktop=$(read_catalog_target "$catalog_yaml" "desktop")
        [[ "$target_desktop" == "true" ]] || continue

        local skill_md="$dir/SKILL.md"
        [[ -f "$skill_md" ]] || continue

        local dest="$DESKTOP_DIR/$name/SKILL.md"
        if [[ ! -f "$dest" ]]; then
            echo -e "  ${RED}[MISSING] $name — not in Desktop dir${NC}"
            diffs=$((diffs + 1))
            continue
        fi
        if ! diff -q "$skill_md" "$dest" &>/dev/null; then
            echo -e "  ${RED}[CHANGED] $name — SKILL.md differs${NC}"
            diff -u "$skill_md" "$dest" 2>/dev/null | head -12 | sed 's/^/    /'
            diffs=$((diffs + 1))
        fi
    done
    if [[ $diffs -eq 0 ]]; then
        echo -e "  ${GREEN}No differences found${NC}"
    else
        echo -e "  ${RED}$diffs item(s) with differences${NC}"
    fi
}

# ── Status ───────────────────────────────────────────────────

show_status() {
    echo -e "\n${CYAN}=== Skill Library Status ===${NC}\n"
    printf "%-40s %-8s %-8s %-20s %-20s %-20s\n" "SKILL" "ORIGIN" "KIND" "CODEX" "CLAUDE" "FACTORY"
    printf "%-40s %-8s %-8s %-20s %-20s %-20s\n" "-----" "------" "----" "-----" "------" "-------"

    local total=0 ok=0 drift=0 missing=0

    for dir in "$LIBRARY_DIR"/*/; do
        [[ -d "$dir" ]] || continue
        local name=$(basename "$dir")
        local catalog_yaml="$dir/catalog.yaml"
        local origin=$(read_catalog_field "$catalog_yaml" "origin")
        local kind=$(read_catalog_field "$catalog_yaml" "kind")

        local codex_s="-" claude_s="-" factory_s="-"

        # Codex
        if [[ "$(read_catalog_target "$catalog_yaml" "codex")" == "true" ]]; then
            local dest="$CODEX_DIR/$name"
            if [[ -L "$dest" ]] || powershell.exe -NoProfile -Command "(Get-Item '$(cygpath -w "$dest")' -Force -ErrorAction SilentlyContinue).Attributes -band [System.IO.FileAttributes]::ReparsePoint" 2>/dev/null | grep -qi "true"; then
                codex_s="OK (junction)"
                ok=$((ok + 1))
            elif [[ -d "$dest" ]]; then
                codex_s="DRIFT (not junction)"
                drift=$((drift + 1))
            else
                codex_s="MISSING"
                missing=$((missing + 1))
            fi
        fi

        # Claude
        if [[ "$(read_catalog_target "$catalog_yaml" "claude")" == "true" ]]; then
            local dest="$CLAUDE_DIR/$name.md"
            if [[ -f "$dest" ]]; then
                if is_autogenerated "$dest"; then
                    claude_s="OK (generated)"
                    ok=$((ok + 1))
                else
                    claude_s="DRIFT (edited)"
                    drift=$((drift + 1))
                fi
            else
                claude_s="MISSING"
                missing=$((missing + 1))
            fi
        fi

        # Factory
        if [[ "$(read_catalog_target "$catalog_yaml" "factory")" == "true" ]]; then
            local dest="$FACTORY_DIR/$name.md"
            if [[ -f "$dest" ]]; then
                if is_autogenerated "$dest"; then
                    factory_s="OK (generated)"
                    ok=$((ok + 1))
                else
                    factory_s="DRIFT (edited)"
                    drift=$((drift + 1))
                fi
            else
                factory_s="MISSING"
                missing=$((missing + 1))
            fi
        fi

        printf "%-40s %-8s %-8s %-20s %-20s %-20s\n" "$name" "$origin" "$kind" "$codex_s" "$claude_s" "$factory_s"
        total=$((total + 1))
    done

    echo ""
    echo -e "${CYAN}Total: $total skills | Synced: $ok | Drift: $drift | Missing: $missing${NC}"
}

# ── Search ─────────────────────────────────────────────────

search_skills() {
    local query="$1"
    if [[ -z "$query" ]]; then
        echo "Usage: $0 search <query>"
        return
    fi
    local found=0
    for dir in "$LIBRARY_DIR"/*/; do
        [[ -d "$dir" ]] || continue
        local name=$(basename "$dir")
        local skill_md="$dir/SKILL.md"
        local catalog_yaml="$dir/catalog.yaml"
        [[ -f "$skill_md" ]] || continue

        local tags=$(read_catalog_field "$catalog_yaml" "tags")
        local scope=$(read_catalog_field "$catalog_yaml" "scope")
        local codex_t=$(read_catalog_target "$catalog_yaml" "codex")
        local claude_t=$(read_catalog_target "$catalog_yaml" "claude")
        local factory_t=$(read_catalog_target "$catalog_yaml" "factory")
        local targets=""
        [[ "$codex_t" == "true" ]] && targets+="codex "
        [[ "$claude_t" == "true" ]] && targets+="claude "
        [[ "$factory_t" == "true" ]] && targets+="factory "

        # Extract description
        local in_fm=$(awk 'BEGIN{p=0} /^---$/{p++; next} p==1{print} p>=2{exit}' "$skill_md")
        local desc_line=$(echo "$in_fm" | grep -n '^description:' | head -1)
        local desc=""
        if [[ -n "$desc_line" ]]; then
            local desc_num=${desc_line%%:*}
            local desc_val=$(echo "$desc_line" | sed 's/^[0-9]*:description:\s*//')
            if echo "$desc_val" | grep -qE '^[>|]-?\s*$'; then
                desc=$(echo "$in_fm" | tail -n +$((desc_num + 1)) | awk '/^[[:space:]]+/{gsub(/^[[:space:]]+/,""); printf "%s ", $0; next} {exit}' | sed 's/ $//')
            else
                desc=$(echo "$desc_val" | tr -d '"')
            fi
        fi

        local searchable="$name $desc $tags"
        if echo "$searchable" | grep -qi "$query"; then
            echo -e "  ${GREEN}$name${NC} ${GRAY}[$targets]${NC}"
            echo -e "    ${GRAY}${desc:0:100}${NC}"
            [[ -n "$tags" ]] && echo -e "    ${CYAN}tags: $tags${NC}"
            [[ "$scope" == "project" ]] && echo -e "    ${YELLOW}scope: project${NC}"
            found=$((found + 1))
        fi
    done
    echo -e "\n${CYAN}$found skill(s) matched '$query'${NC}"
}

# ── Main ───────────────────────────────────────────────────

COMMAND="${1:-}"
TARGET="${2:-all}"

if [[ -z "$COMMAND" ]]; then
    echo "Usage: $0 {push|pull|status} [codex|claude|factory|all]"
    exit 1
fi

echo -e "${CYAN}Skill Library Sync${NC}"
echo -e "${GRAY}Library: $LIBRARY_DIR${NC}"

case "$COMMAND" in
    push)
        [[ "$TARGET" == "all" || "$TARGET" == "codex" ]]   && push_codex
        [[ "$TARGET" == "all" || "$TARGET" == "claude" ]]   && push_claude
        [[ "$TARGET" == "all" || "$TARGET" == "factory" ]]  && push_factory
        [[ "$TARGET" == "all" || "$TARGET" == "desktop" ]]  && push_desktop
        update_catalog_json
        echo -e "\n${GREEN}Push complete.${NC}"
        ;;
    pull)
        [[ "$TARGET" == "all" || "$TARGET" == "codex" ]]   && pull_codex
        [[ "$TARGET" == "all" || "$TARGET" == "claude" ]]   && pull_claude
        [[ "$TARGET" == "all" || "$TARGET" == "factory" ]]  && pull_factory
        update_catalog_json
        echo -e "\n${GREEN}Pull complete.${NC}"
        ;;
    status)
        show_status
        ;;
    diff)
        [[ "$TARGET" == "all" || "$TARGET" == "codex" ]]   && diff_codex
        [[ "$TARGET" == "all" || "$TARGET" == "claude" ]]   && diff_claude
        [[ "$TARGET" == "all" || "$TARGET" == "factory" ]]  && diff_factory
        [[ "$TARGET" == "all" || "$TARGET" == "desktop" ]]  && diff_desktop
        ;;
    search)
        search_skills "$TARGET"
        ;;
    *)
        echo "Unknown command: $COMMAND"
        echo "Usage: $0 {push|pull|status|diff|search} [codex|claude|factory|all|<query>]"
        exit 1
        ;;
esac
