<#
.SYNOPSIS
    Syncs the centralized skill library to/from tool-specific directories.

.DESCRIPTION
    Manages synchronization between ~/skill-library (single source of truth)
    and the native directories for Codex, Claude Code, and Factory.

    Codex:   Directory junctions (bidirectional, zero-copy)
    Claude:  Generated .md command files (frontmatter stripped)
    Factory: Generated .md droid files (frontmatter preserved)

.PARAMETER Command
    push   - Library -> tool directories
    pull   - Import new skills from tool directories into library
    status - Show sync state for all skills
    diff   - Show content differences between library and tool directories

.PARAMETER Target
    Optional filter: codex, claude, factory, desktop, or all (default).
    desktop = Claude desktop app (Cowork) skills folder; push/diff only, one-way.

.EXAMPLE
    .\sync.ps1 push
    .\sync.ps1 push -Target codex
    .\sync.ps1 pull
    .\sync.ps1 status
    .\sync.ps1 diff
    .\sync.ps1 diff -Target factory
#>

param(
    [Parameter(Position = 0, Mandatory = $true)]
    [ValidateSet("push", "pull", "status", "diff", "search", "lint")]
    [string]$Command,

    [Parameter(Position = 1)]
    [string]$Target = "all"
)

$ErrorActionPreference = "Stop"

# --- Paths ---
$LibraryDir  = Join-Path $env:USERPROFILE "skill-library"
$CodexDir    = Join-Path $env:USERPROFILE ".codex\skills"
$ClaudeDir   = Join-Path $env:USERPROFILE ".claude\commands"
$FactoryDir  = Join-Path $env:USERPROFILE ".factory\droids"
# Claude desktop app (Cowork) skills. NOTE: the two GUID segments are tied to the
# current app install; if the desktop app reinstalls and Push-Desktop reports the
# dir missing, find the new path with:
#   Get-ChildItem "$env:APPDATA\Claude\local-agent-mode-sessions\skills-plugin" -Recurse -Directory -Filter skills
# and update this one line. Library -> desktop is ONE-WAY; desktop edits get overwritten.
$DesktopDir  = Join-Path $env:APPDATA "Claude\local-agent-mode-sessions\skills-plugin\c6f03819-82ac-4592-af90-11a16ffe8d62\86adc332-a4c3-440b-9c09-a8f0d4221001\skills"

$AutoGenMarker = "<!-- AUTO-GENERATED from skill-library. Do not edit directly. -->"

# --- Helpers ---

function Read-CatalogYaml {
    param([string]$Path)
    $result = @{}
    if (-not (Test-Path $Path)) { return $result }
    $content = Get-Content $Path -Raw
    foreach ($line in $content -split "`n") {
        $line = $line.Trim()
        if ($line -match "^(\w[\w.-]*)\s*:\s*(.+)$") {
            $key = $Matches[1]
            $val = $Matches[2].Trim()
            # Parse booleans
            if ($val -eq "true") { $val = $true }
            elseif ($val -eq "false") { $val = $false }
            # Parse arrays like [a, b, c]
            elseif ($val -match "^\[(.+)\]$") {
                $val = ($Matches[1] -split ",") | ForEach-Object { $_.Trim() }
            }
            $result[$key] = $val
        }
    }
    # Parse nested targets block
    if ($content -match "(?ms)targets:\s*\n((?:\s+\w+:.*\n?)+)") {
        $targets = @{}
        foreach ($tline in ($Matches[1] -split "`n")) {
            $tline = $tline.Trim()
            if ($tline -match "^(\w+)\s*:\s*(true|false)$") {
                $targets[$Matches[1]] = ($Matches[2] -eq "true")
            }
        }
        $result["targets"] = $targets
    }
    return $result
}

function Get-SkillMdBody {
    param([string]$Path)
    $content = Get-Content $Path -Raw
    # Strip YAML frontmatter if present
    if ($content -match "(?ms)^---\s*\n.*?\n---\s*\n(.*)$") {
        return $Matches[1].TrimStart()
    }
    return $content
}

function Get-SkillMdFull {
    param([string]$Path)
    return Get-Content $Path -Raw
}

function Test-IsJunction {
    param([string]$Path)
    if (-not (Test-Path $Path)) { return $false }
    $item = Get-Item $Path -Force
    return ($item.Attributes -band [System.IO.FileAttributes]::ReparsePoint)
}

function Get-JunctionTarget {
    param([string]$Path)
    if (-not (Test-IsJunction $Path)) { return $null }
    $item = Get-Item $Path -Force
    return $item.Target
}

function Test-IsAutoGenerated {
    param([string]$Path)
    if (-not (Test-Path $Path)) { return $false }
    # Marker is on line 1 (Factory/legacy) or just below the frontmatter (Claude commands)
    $head = Get-Content $Path -TotalCount 30
    return (@($head) -contains $AutoGenMarker)
}

# --- Catalog JSON generation ---

function Update-CatalogJson {
    $skills = @()
    foreach ($dir in (Get-ChildItem $LibraryDir -Directory)) {
        $skillMd = Join-Path $dir.FullName "SKILL.md"
        $catalogYaml = Join-Path $dir.FullName "catalog.yaml"
        if (-not (Test-Path $skillMd)) { continue }

        $catalog = Read-CatalogYaml $catalogYaml

        # Extract description from SKILL.md frontmatter
        $content = Get-Content $skillMd -Raw
        $description = ""
        # Extract frontmatter block
        if ($content -match '(?ms)^---\s*\n(.*?)\n---') {
            $fm = $Matches[1]
            $fmLines = $fm -split "`n"
            for ($i = 0; $i -lt $fmLines.Count; $i++) {
                $fmLine = $fmLines[$i]
                if ($fmLine -match '^description:\s*(.*)$') {
                    $val = $Matches[1].Trim()
                    if ($val -match '^[>|]-?\s*$') {
                        # Multi-line scalar (>- or |- or > or |): collect indented continuation lines
                        $parts = @()
                        for ($j = $i + 1; $j -lt $fmLines.Count; $j++) {
                            if ($fmLines[$j] -match '^\s+(.+)') {
                                $parts += $Matches[1].Trim()
                            } else { break }
                        }
                        $description = ($parts -join ' ').Trim()
                    }
                    elseif ($val -match '^"(.+)"$') {
                        $description = $Matches[1]
                    }
                    else {
                        $description = $val.Trim('"')
                    }
                    break
                }
            }
        }

        $skill = [ordered]@{
            id          = $dir.Name
            description = $description
            origin      = if ($catalog["origin"]) { $catalog["origin"] } else { "unknown" }
            kind        = if ($catalog["kind"]) { $catalog["kind"] } else { "skill" }
            tags        = if ($catalog["tags"]) { @($catalog["tags"]) } else { @() }
            targets     = if ($catalog["targets"]) { $catalog["targets"] } else { @{ codex = $false; claude = $false; factory = $false } }
            hasScripts    = (Test-Path (Join-Path $dir.FullName "scripts"))
            hasReferences = (Test-Path (Join-Path $dir.FullName "references"))
            hasAssets     = (Test-Path (Join-Path $dir.FullName "assets"))
            path        = "$($dir.Name)/"
        }
        $skills += $skill
    }

    $byOrigin = @{}; $byKind = @{}
    foreach ($s in $skills) {
        $o = $s.origin; $k = $s.kind
        if (-not $byOrigin.ContainsKey($o)) { $byOrigin[$o] = 0 }
        $byOrigin[$o] = $byOrigin[$o] + 1
        if (-not $byKind.ContainsKey($k)) { $byKind[$k] = 0 }
        $byKind[$k] = $byKind[$k] + 1
    }

    $catalog = [ordered]@{
        version   = 1
        generated = (Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ")
        skills    = $skills
        stats     = [ordered]@{
            total    = $skills.Count
            byOrigin = $byOrigin
            byKind   = $byKind
        }
    }

    $json = $catalog | ConvertTo-Json -Depth 5
    Set-Content (Join-Path $LibraryDir "catalog.json") $json -Encoding UTF8
    Write-Host "  Updated catalog.json ($($skills.Count) skills)" -ForegroundColor Cyan
}

# --- Push ---

function Push-Codex {
    Write-Host "`n[Codex] Syncing via directory junctions..." -ForegroundColor Yellow
    $count = 0
    foreach ($dir in (Get-ChildItem $LibraryDir -Directory)) {
        # Skip backup artifacts left behind by previous push runs
        if ($dir.Name -match '\.bak(\.|$)') { continue }
        $catalogYaml = Join-Path $dir.FullName "catalog.yaml"
        $catalog = Read-CatalogYaml $catalogYaml
        $targets = $catalog["targets"]
        if (-not $targets -or -not $targets["codex"]) { continue }

        $dest = Join-Path $CodexDir $dir.Name

        if (Test-IsJunction $dest) {
            $jTarget = Get-JunctionTarget $dest
            if ($jTarget -eq $dir.FullName) {
                Write-Host "  [OK] $($dir.Name) — junction exists" -ForegroundColor DarkGray
                $count++
                continue
            }
            else {
                Write-Host "  [FIX] $($dir.Name) — junction points elsewhere, replacing" -ForegroundColor DarkYellow
                (Get-Item $dest).Delete()
            }
        }
        elseif (Test-Path $dest) {
            $backup = "$dest.bak"
            Write-Host "  [BACKUP] $($dir.Name) — backing up original to $($dir.Name).bak" -ForegroundColor DarkYellow
            if (Test-Path $backup) { Remove-Item $backup -Recurse -Force }
            Rename-Item $dest $backup
        }

        # Create junction (no admin required)
        cmd /c "mklink /J `"$dest`" `"$($dir.FullName)`"" | Out-Null
        Write-Host "  [NEW] $($dir.Name) — junction created" -ForegroundColor Green
        $count++
    }
    Write-Host "  Codex: $count skills synced" -ForegroundColor Cyan
}

function Push-Claude {
    Write-Host "`n[Claude] Generating command files..." -ForegroundColor Yellow
    $count = 0
    foreach ($dir in (Get-ChildItem $LibraryDir -Directory)) {
        $catalogYaml = Join-Path $dir.FullName "catalog.yaml"
        $catalog = Read-CatalogYaml $catalogYaml
        $targets = $catalog["targets"]
        if (-not $targets -or -not $targets["claude"]) { continue }

        $skillMd = Join-Path $dir.FullName "SKILL.md"
        if (-not (Test-Path $skillMd)) { continue }

        $dest = Join-Path $ClaudeDir "$($dir.Name).md"

        # Frontmatter must stay at line 1 so Claude Code surfaces the description;
        # the auto-gen marker goes between frontmatter and body.
        $full = Get-SkillMdFull $skillMd
        if ($full -match "(?ms)^(---\s*\n.*?\n---\s*\n)(.*)$") {
            $output = "$($Matches[1])$AutoGenMarker`n`n$($Matches[2].TrimStart())"
        } else {
            $output = "$AutoGenMarker`n`n$full"
        }
        # BOM-less UTF-8: a BOM before the opening --- breaks frontmatter parsing
        [System.IO.File]::WriteAllText($dest, $output)
        Write-Host "  [GEN] $($dir.Name).md" -ForegroundColor Green
        $count++
    }
    Write-Host "  Claude: $count commands synced" -ForegroundColor Cyan
}

function Push-Factory {
    Write-Host "`n[Factory] Generating droid files..." -ForegroundColor Yellow
    $count = 0
    foreach ($dir in (Get-ChildItem $LibraryDir -Directory)) {
        $catalogYaml = Join-Path $dir.FullName "catalog.yaml"
        $catalog = Read-CatalogYaml $catalogYaml
        $targets = $catalog["targets"]
        if (-not $targets -or -not $targets["factory"]) { continue }

        $skillMd = Join-Path $dir.FullName "SKILL.md"
        if (-not (Test-Path $skillMd)) { continue }

        # Factory droids need the full file including frontmatter
        $full = Get-SkillMdFull $skillMd
        $dest = Join-Path $FactoryDir "$($dir.Name).md"

        # Insert auto-gen marker as HTML comment before frontmatter
        $output = "$AutoGenMarker`n$full"
        Set-Content $dest $output -Encoding UTF8 -NoNewline
        Write-Host "  [GEN] $($dir.Name).md" -ForegroundColor Green
        $count++
    }
    Write-Host "  Factory: $count droids synced" -ForegroundColor Cyan
}

function Push-Desktop {
    Write-Host "`n[Desktop] Copying skill directories to Claude desktop app..." -ForegroundColor Yellow
    if (-not (Test-Path $DesktopDir)) {
        Write-Host "  [SKIP] Desktop skills dir not found: $DesktopDir" -ForegroundColor DarkYellow
        Write-Host "  The app install GUIDs may have changed; see the comment above `$DesktopDir in this script." -ForegroundColor DarkYellow
        return
    }
    $count = 0
    foreach ($dir in (Get-ChildItem $LibraryDir -Directory)) {
        if ($dir.Name -match '\.bak(\.|$)') { continue }
        $catalogYaml = Join-Path $dir.FullName "catalog.yaml"
        $catalog = Read-CatalogYaml $catalogYaml
        $targets = $catalog["targets"]
        if (-not $targets -or -not $targets["desktop"]) { continue }

        $skillMd = Join-Path $dir.FullName "SKILL.md"
        if (-not (Test-Path $skillMd)) { continue }

        # Mirror the skill directory, minus library-only metadata.
        # Only desktop-targeted skills are touched; app-managed stock skills
        # (docx, pptx, skill-creator, ...) are never desktop targets.
        $dest = Join-Path $DesktopDir $dir.Name
        if (Test-Path $dest) { Remove-Item $dest -Recurse -Force }
        New-Item $dest -ItemType Directory | Out-Null
        foreach ($item in (Get-ChildItem $dir.FullName -Force)) {
            if ($item.Name -eq "catalog.yaml") { continue }
            Copy-Item $item.FullName -Destination $dest -Recurse
        }
        Write-Host "  [GEN] $($dir.Name)/" -ForegroundColor Green
        $count++
    }
    Write-Host "  Desktop: $count skills synced" -ForegroundColor Cyan
}

# --- Pull ---

function Pull-Codex {
    Write-Host "`n[Codex] Scanning for new skills..." -ForegroundColor Yellow
    $imported = 0
    foreach ($dir in (Get-ChildItem $CodexDir -Directory)) {
        if ($dir.Name -eq ".system") { continue }
        if (Test-IsJunction $dir.FullName) { continue }  # Already managed
        # Skip backup artifacts produced by push (prevents .bak.bak.bak loop)
        if ($dir.Name -match '\.bak(\.|$)') { continue }

        $libDest = Join-Path $LibraryDir $dir.Name
        if (Test-Path $libDest) { continue }  # Already in library

        Write-Host "  [IMPORT] $($dir.Name) — new Codex skill" -ForegroundColor Green
        Copy-Item $dir.FullName $libDest -Recurse

        # Create catalog.yaml
        $catalogContent = @"
id: $($dir.Name)
origin: codex
kind: skill
tags: []
targets:
  codex: true
  claude: false
  factory: false
"@
        Set-Content (Join-Path $libDest "catalog.yaml") $catalogContent -Encoding UTF8
        $imported++
    }
    Write-Host "  Codex: $imported new skills imported" -ForegroundColor Cyan
}

function Pull-Claude {
    Write-Host "`n[Claude] Scanning for new/updated commands..." -ForegroundColor Yellow
    $imported = 0
    $updated = 0
    foreach ($file in (Get-ChildItem $ClaudeDir -Filter "*.md")) {
        if (Test-IsAutoGenerated $file.FullName) { continue }  # Skip auto-generated

        $name = $file.BaseName
        $libDest = Join-Path $LibraryDir $name
        if (Test-Path $libDest) {
            # Existing skill — check if Claude version has diverged
            $libSkill = Join-Path $libDest "SKILL.md"
            if (Test-Path $libSkill) {
                $libBody = (Get-SkillMdBody $libSkill).TrimEnd()
                $claudeBody = (Get-Content $file.FullName -Raw).TrimEnd()
                if ($libBody -ne $claudeBody) {
                    Write-Host "  [UPDATE] $name — Claude version differs, updating library" -ForegroundColor DarkYellow
                    # Preserve frontmatter, replace body
                    $libContent = Get-Content $libSkill -Raw
                    if ($libContent -match '(?ms)^(---\s*\n.*?\n---\s*\n)') {
                        $frontmatter = $Matches[1]
                        Set-Content $libSkill "$frontmatter$claudeBody" -Encoding UTF8 -NoNewline
                    }
                    $updated++
                }
            }
            continue
        }

        Write-Host "  [IMPORT] $name — new Claude command" -ForegroundColor Green
        New-Item $libDest -ItemType Directory -Force | Out-Null

        $body = Get-Content $file.FullName -Raw
        $firstLine = ($body -split "`n")[0].Trim()
        $desc = if ($firstLine.Length -gt 120) { $firstLine.Substring(0, 120) } else { $firstLine }

        $skillContent = @"
---
name: "$name"
description: "$desc"
---
$body
"@
        Set-Content (Join-Path $libDest "SKILL.md") $skillContent -Encoding UTF8

        $catalogContent = @"
id: $name
origin: claude
kind: command
tags: []
targets:
  codex: false
  claude: true
  factory: false
"@
        Set-Content (Join-Path $libDest "catalog.yaml") $catalogContent -Encoding UTF8
        $imported++
    }
    Write-Host "  Claude: $imported new, $updated updated" -ForegroundColor Cyan
}

function Pull-Factory {
    Write-Host "`n[Factory] Scanning for new/updated droids..." -ForegroundColor Yellow
    $imported = 0
    $updated = 0
    foreach ($file in (Get-ChildItem $FactoryDir -Filter "*.md")) {
        if (Test-IsAutoGenerated $file.FullName) { continue }

        $name = $file.BaseName
        $libDest = Join-Path $LibraryDir $name
        if (Test-Path $libDest) {
            # Existing skill — check if Factory version has diverged
            $libSkill = Join-Path $libDest "SKILL.md"
            if (Test-Path $libSkill) {
                $libFull = (Get-SkillMdFull $libSkill).TrimEnd()
                $factoryFull = (Get-Content $file.FullName -Raw).TrimEnd()
                if ($libFull -ne $factoryFull) {
                    Write-Host "  [UPDATE] $name — Factory version differs, updating library" -ForegroundColor DarkYellow
                    Copy-Item $file.FullName $libSkill -Force
                    $updated++
                }
            }
            continue
        }

        Write-Host "  [IMPORT] $name — new Factory droid" -ForegroundColor Green
        New-Item $libDest -ItemType Directory -Force | Out-Null
        Copy-Item $file.FullName (Join-Path $libDest "SKILL.md")

        $catalogContent = @"
id: $name
origin: factory
kind: droid
tags: []
targets:
  codex: false
  claude: false
  factory: true
"@
        Set-Content (Join-Path $libDest "catalog.yaml") $catalogContent -Encoding UTF8
        $imported++
    }
    Write-Host "  Factory: $imported new, $updated updated" -ForegroundColor Cyan
}

# --- Status ---

function Show-Status {
    Write-Host "`n=== Skill Library Status ===" -ForegroundColor Cyan
    Write-Host ""

    $results = @()
    foreach ($dir in (Get-ChildItem $LibraryDir -Directory | Sort-Object Name)) {
        $catalogYaml = Join-Path $dir.FullName "catalog.yaml"
        $catalog = Read-CatalogYaml $catalogYaml
        $targets = $catalog["targets"]
        if (-not $targets) { $targets = @{} }

        $codexStatus = "-"
        $claudeStatus = "-"
        $factoryStatus = "-"

        # Codex
        if ($targets["codex"]) {
            $dest = Join-Path $CodexDir $dir.Name
            if (Test-IsJunction $dest) {
                $jTarget = Get-JunctionTarget $dest
                if ($jTarget -eq $dir.FullName) { $codexStatus = "OK (junction)" }
                else { $codexStatus = "DRIFT (wrong target)" }
            }
            elseif (Test-Path $dest) { $codexStatus = "DRIFT (not junction)" }
            else { $codexStatus = "MISSING" }
        }

        # Claude
        if ($targets["claude"]) {
            $dest = Join-Path $ClaudeDir "$($dir.Name).md"
            if (Test-Path $dest) {
                if (Test-IsAutoGenerated $dest) { $claudeStatus = "OK (generated)" }
                else { $claudeStatus = "DRIFT (manually edited)" }
            }
            else { $claudeStatus = "MISSING" }
        }

        # Factory
        if ($targets["factory"]) {
            $dest = Join-Path $FactoryDir "$($dir.Name).md"
            if (Test-Path $dest) {
                if (Test-IsAutoGenerated $dest) { $factoryStatus = "OK (generated)" }
                else { $factoryStatus = "DRIFT (manually edited)" }
            }
            else { $factoryStatus = "MISSING" }
        }

        $origin = if ($catalog["origin"]) { $catalog["origin"] } else { "?" }
        $kind = if ($catalog["kind"]) { $catalog["kind"] } else { "?" }

        $results += [PSCustomObject]@{
            Skill   = $dir.Name
            Origin  = $origin
            Kind    = $kind
            Codex   = $codexStatus
            Claude  = $claudeStatus
            Factory = $factoryStatus
        }
    }

    $results | Format-Table -AutoSize

    # Summary
    $total = $results.Count
    $ok = ($results | Where-Object { $_.Codex -like "OK*" -or $_.Claude -like "OK*" -or $_.Factory -like "OK*" }).Count
    $drift = ($results | Where-Object { $_.Codex -like "DRIFT*" -or $_.Claude -like "DRIFT*" -or $_.Factory -like "DRIFT*" }).Count
    $missing = ($results | Where-Object { $_.Codex -eq "MISSING" -or $_.Claude -eq "MISSING" -or $_.Factory -eq "MISSING" }).Count

    Write-Host "Total: $total skills | Synced: $ok | Drift: $drift | Missing: $missing" -ForegroundColor Cyan

    # Check for unmanaged skills in tool directories
    Write-Host "`n--- Unmanaged items in tool directories ---" -ForegroundColor Yellow
    $unmanaged = 0
    foreach ($dir in (Get-ChildItem $CodexDir -Directory)) {
        if ($dir.Name -eq ".system") { continue }
        if (Test-IsJunction $dir.FullName) { continue }
        $libPath = Join-Path $LibraryDir $dir.Name
        if (-not (Test-Path $libPath)) {
            Write-Host "  Codex: $($dir.Name) (not in library — run 'pull' to import)" -ForegroundColor DarkYellow
            $unmanaged++
        }
    }
    foreach ($file in (Get-ChildItem $ClaudeDir -Filter "*.md" -ErrorAction SilentlyContinue)) {
        if (Test-IsAutoGenerated $file.FullName) { continue }
        $libPath = Join-Path $LibraryDir $file.BaseName
        if (-not (Test-Path $libPath)) {
            Write-Host "  Claude: $($file.BaseName) (not in library — run 'pull' to import)" -ForegroundColor DarkYellow
            $unmanaged++
        }
    }
    foreach ($file in (Get-ChildItem $FactoryDir -Filter "*.md" -ErrorAction SilentlyContinue)) {
        if (Test-IsAutoGenerated $file.FullName) { continue }
        $libPath = Join-Path $LibraryDir $file.BaseName
        if (-not (Test-Path $libPath)) {
            Write-Host "  Factory: $($file.BaseName) (not in library — run 'pull' to import)" -ForegroundColor DarkYellow
            $unmanaged++
        }
    }
    if ($unmanaged -eq 0) {
        Write-Host "  None — all tool skills are tracked in the library" -ForegroundColor Green
    }
}

# --- Diff ---

function Diff-Codex {
    Write-Host "`n[Codex] Checking for content differences..." -ForegroundColor Yellow
    $diffs = 0
    foreach ($dir in (Get-ChildItem $LibraryDir -Directory)) {
        $catalogYaml = Join-Path $dir.FullName "catalog.yaml"
        $catalog = Read-CatalogYaml $catalogYaml
        $targets = $catalog["targets"]
        if (-not $targets -or -not $targets["codex"]) { continue }

        $dest = Join-Path $CodexDir $dir.Name
        if (-not (Test-Path $dest)) {
            Write-Host "  [MISSING] $($dir.Name) — not in Codex dir" -ForegroundColor Red
            $diffs++
            continue
        }
        if (Test-IsJunction $dest) {
            $jTarget = Get-JunctionTarget $dest
            if ($jTarget -eq $dir.FullName) {
                # Junction points to library — content is identical by definition
                continue
            }
            Write-Host "  [WRONG TARGET] $($dir.Name) — junction points to $jTarget" -ForegroundColor Red
            $diffs++
        }
        else {
            # Regular directory — compare SKILL.md content
            $libSkill = Join-Path $dir.FullName "SKILL.md"
            $destSkill = Join-Path $dest "SKILL.md"
            if ((Test-Path $libSkill) -and (Test-Path $destSkill)) {
                $libContent = Get-Content $libSkill -Raw
                $destContent = Get-Content $destSkill -Raw
                if ($libContent -ne $destContent) {
                    Write-Host "  [CHANGED] $($dir.Name) — SKILL.md differs (not a junction)" -ForegroundColor Red
                    $libLines = $libContent -split "`n"
                    $destLines = $destContent -split "`n"
                    $compared = Compare-Object $libLines $destLines
                    foreach ($c in ($compared | Select-Object -First 10)) {
                        $indicator = if ($c.SideIndicator -eq "<=") { "-lib" } else { "+codex" }
                        Write-Host "    $indicator $($c.InputObject.TrimEnd())" -ForegroundColor DarkGray
                    }
                    if ($compared.Count -gt 10) {
                        Write-Host "    ... and $($compared.Count - 10) more differences" -ForegroundColor DarkGray
                    }
                    $diffs++
                }
            }
        }
    }
    if ($diffs -eq 0) {
        Write-Host "  No differences found" -ForegroundColor Green
    } else {
        Write-Host "  $diffs skill(s) with differences" -ForegroundColor Red
    }
}

function Diff-Claude {
    Write-Host "`n[Claude] Checking for content differences..." -ForegroundColor Yellow
    $diffs = 0
    foreach ($dir in (Get-ChildItem $LibraryDir -Directory)) {
        $catalogYaml = Join-Path $dir.FullName "catalog.yaml"
        $catalog = Read-CatalogYaml $catalogYaml
        $targets = $catalog["targets"]
        if (-not $targets -or -not $targets["claude"]) { continue }

        $skillMd = Join-Path $dir.FullName "SKILL.md"
        if (-not (Test-Path $skillMd)) { continue }

        $dest = Join-Path $ClaudeDir "$($dir.Name).md"
        if (-not (Test-Path $dest)) {
            Write-Host "  [MISSING] $($dir.Name).md — not in Claude dir" -ForegroundColor Red
            $diffs++
            continue
        }

        # Compare: library body vs deployed file (minus frontmatter and auto-gen marker)
        $libBody = Get-SkillMdBody $skillMd
        $deployedContent = Get-Content $dest -Raw
        if ($deployedContent -match "(?ms)^---\s*\n.*?\n---\s*\n(.*)$") {
            $deployedContent = $Matches[1]
        }
        $deployedBody = ($deployedContent -replace "(?ms)^$([regex]::Escape($AutoGenMarker))\s*\n*", "").TrimStart()

        if ($libBody.TrimEnd() -ne $deployedBody.TrimEnd()) {
            Write-Host "  [CHANGED] $($dir.Name).md" -ForegroundColor Red
            $libLines = $libBody -split "`n"
            $destLines = $deployedBody -split "`n"
            $compared = Compare-Object $libLines $destLines
            foreach ($c in ($compared | Select-Object -First 8)) {
                $indicator = if ($c.SideIndicator -eq "<=") { "-lib" } else { "+claude" }
                Write-Host "    $indicator $($c.InputObject.TrimEnd())" -ForegroundColor DarkGray
            }
            if ($compared.Count -gt 8) {
                Write-Host "    ... and $($compared.Count - 8) more differences" -ForegroundColor DarkGray
            }
            $diffs++
        }
    }

    # Check for unmanaged files in Claude dir
    foreach ($file in (Get-ChildItem $ClaudeDir -Filter "*.md" -ErrorAction SilentlyContinue)) {
        if (Test-IsAutoGenerated $file.FullName) { continue }
        $libPath = Join-Path $LibraryDir $file.BaseName
        if (-not (Test-Path $libPath)) {
            Write-Host "  [UNTRACKED] $($file.Name) — exists in Claude but not in library" -ForegroundColor DarkYellow
            $diffs++
        }
    }

    if ($diffs -eq 0) {
        Write-Host "  No differences found" -ForegroundColor Green
    } else {
        Write-Host "  $diffs item(s) with differences" -ForegroundColor Red
    }
}

function Diff-Factory {
    Write-Host "`n[Factory] Checking for content differences..." -ForegroundColor Yellow
    $diffs = 0
    foreach ($dir in (Get-ChildItem $LibraryDir -Directory)) {
        $catalogYaml = Join-Path $dir.FullName "catalog.yaml"
        $catalog = Read-CatalogYaml $catalogYaml
        $targets = $catalog["targets"]
        if (-not $targets -or -not $targets["factory"]) { continue }

        $skillMd = Join-Path $dir.FullName "SKILL.md"
        if (-not (Test-Path $skillMd)) { continue }

        $dest = Join-Path $FactoryDir "$($dir.Name).md"
        if (-not (Test-Path $dest)) {
            Write-Host "  [MISSING] $($dir.Name).md — not in Factory dir" -ForegroundColor Red
            $diffs++
            continue
        }

        # Compare: full library SKILL.md vs deployed file (minus auto-gen marker)
        $libFull = (Get-SkillMdFull $skillMd).TrimEnd()
        $deployedContent = Get-Content $dest -Raw
        $deployedBody = ($deployedContent -replace "(?ms)^$([regex]::Escape($AutoGenMarker))\s*\n*", "").TrimEnd()

        if ($libFull -ne $deployedBody) {
            $libLen = $libFull.Length
            $depLen = $deployedBody.Length
            Write-Host "  [CHANGED] $($dir.Name).md (library: ${libLen} chars, factory: ${depLen} chars)" -ForegroundColor Red
            $libLines = $libFull -split "`n"
            $destLines = $deployedBody -split "`n"
            $compared = Compare-Object $libLines $destLines
            foreach ($c in ($compared | Select-Object -First 8)) {
                $indicator = if ($c.SideIndicator -eq "<=") { "-lib" } else { "+factory" }
                Write-Host "    $indicator $($c.InputObject.TrimEnd())" -ForegroundColor DarkGray
            }
            if ($compared.Count -gt 8) {
                Write-Host "    ... and $($compared.Count - 8) more differences" -ForegroundColor DarkGray
            }
            $diffs++
        }
    }

    # Check for unmanaged files in Factory dir
    foreach ($file in (Get-ChildItem $FactoryDir -Filter "*.md" -ErrorAction SilentlyContinue)) {
        if (Test-IsAutoGenerated $file.FullName) { continue }
        $libPath = Join-Path $LibraryDir $file.BaseName
        if (-not (Test-Path $libPath)) {
            Write-Host "  [UNTRACKED] $($file.Name) — exists in Factory but not in library" -ForegroundColor DarkYellow
            $diffs++
        }
    }

    if ($diffs -eq 0) {
        Write-Host "  No differences found" -ForegroundColor Green
    } else {
        Write-Host "  $diffs item(s) with differences" -ForegroundColor Red
    }
}

function Diff-Desktop {
    Write-Host "`n[Desktop] Checking for content differences..." -ForegroundColor Yellow
    if (-not (Test-Path $DesktopDir)) {
        Write-Host "  [SKIP] Desktop skills dir not found: $DesktopDir" -ForegroundColor DarkYellow
        return
    }
    $diffs = 0
    foreach ($dir in (Get-ChildItem $LibraryDir -Directory)) {
        $catalogYaml = Join-Path $dir.FullName "catalog.yaml"
        $catalog = Read-CatalogYaml $catalogYaml
        $targets = $catalog["targets"]
        if (-not $targets -or -not $targets["desktop"]) { continue }

        $libSkill = Join-Path $dir.FullName "SKILL.md"
        if (-not (Test-Path $libSkill)) { continue }

        $destSkill = Join-Path (Join-Path $DesktopDir $dir.Name) "SKILL.md"
        if (-not (Test-Path $destSkill)) {
            Write-Host "  [MISSING] $($dir.Name) — not in Desktop dir" -ForegroundColor Red
            $diffs++
            continue
        }

        $libContent = (Get-SkillMdFull $libSkill).TrimEnd()
        $destContent = (Get-Content $destSkill -Raw).TrimEnd()
        if ($libContent -ne $destContent) {
            Write-Host "  [CHANGED] $($dir.Name) — SKILL.md differs" -ForegroundColor Red
            $compared = Compare-Object ($libContent -split "`n") ($destContent -split "`n")
            foreach ($c in ($compared | Select-Object -First 8)) {
                $indicator = if ($c.SideIndicator -eq "<=") { "-lib" } else { "+desktop" }
                Write-Host "    $indicator $($c.InputObject.TrimEnd())" -ForegroundColor DarkGray
            }
            if ($compared.Count -gt 8) {
                Write-Host "    ... and $($compared.Count - 8) more differences" -ForegroundColor DarkGray
            }
            $diffs++
        }
    }
    if ($diffs -eq 0) {
        Write-Host "  No differences found" -ForegroundColor Green
    } else {
        Write-Host "  $diffs item(s) with differences" -ForegroundColor Red
    }
}

# --- Search ---

function Search-Skills {
    param([string]$Query)
    if (-not $Query) {
        Write-Host "Usage: .\sync.ps1 search <query>" -ForegroundColor Yellow
        return
    }
    $pattern = [regex]::Escape($Query)
    $found = 0
    foreach ($dir in (Get-ChildItem $LibraryDir -Directory | Sort-Object Name)) {
        $catalogYaml = Join-Path $dir.FullName "catalog.yaml"
        $skillMd = Join-Path $dir.FullName "SKILL.md"
        if (-not (Test-Path $skillMd)) { continue }

        $catalog = Read-CatalogYaml $catalogYaml
        $name = $dir.Name
        $tags = if ($catalog["tags"]) { $catalog["tags"] -join ", " } else { "" }
        $scope = if ($catalog["scope"]) { $catalog["scope"] } else { "" }
        $targets = $catalog["targets"]
        $targetList = @()
        if ($targets) {
            if ($targets["codex"]) { $targetList += "codex" }
            if ($targets["claude"]) { $targetList += "claude" }
            if ($targets["factory"]) { $targetList += "factory" }
        }

        # Extract description
        $content = Get-Content $skillMd -Raw
        $description = ""
        if ($content -match '(?ms)^---\s*\n(.*?)\n---') {
            $fm = $Matches[1]
            $fmLines = $fm -split "`n"
            for ($i = 0; $i -lt $fmLines.Count; $i++) {
                if ($fmLines[$i] -match '^description:\s*(.*)$') {
                    $val = $Matches[1].Trim()
                    if ($val -match '^[>|]-?\s*$') {
                        $parts = @()
                        for ($j = $i + 1; $j -lt $fmLines.Count; $j++) {
                            if ($fmLines[$j] -match '^\s+(.+)') { $parts += $Matches[1].Trim() } else { break }
                        }
                        $description = ($parts -join ' ').Trim()
                    } elseif ($val -match '^"(.+)"$') { $description = $Matches[1] }
                    else { $description = $val.Trim('"') }
                    break
                }
            }
        }

        $searchable = "$name $description $tags"
        if ($searchable -match $pattern) {
            $targetStr = $targetList -join ", "
            Write-Host "  $name" -ForegroundColor Green -NoNewline
            Write-Host " [$targetStr]" -ForegroundColor DarkGray
            if ($description.Length -gt 100) { $description = $description.Substring(0, 100) + "..." }
            Write-Host "    $description" -ForegroundColor Gray
            if ($tags) { Write-Host "    tags: $tags" -ForegroundColor DarkCyan }
            if ($scope -eq "project") { Write-Host "    scope: project" -ForegroundColor DarkYellow }
            $found++
        }
    }
    Write-Host "`n$found skill(s) matched '$Query'" -ForegroundColor Cyan
}

# --- Lint ---

function Invoke-Lint {
    Write-Host "`n=== Skill Library Lint ===" -ForegroundColor Cyan

    # --- Pass 1: discover all skills and their catalog.yaml metadata.
    # Needed upfront so related_exists / related_bidirectional can cross-reference.
    $allSkills = @{}
    foreach ($dir in (Get-ChildItem $LibraryDir -Directory | Sort-Object Name)) {
        $catalogYaml = Join-Path $dir.FullName "catalog.yaml"
        $skillMd = Join-Path $dir.FullName "SKILL.md"
        if (-not (Test-Path $skillMd)) { continue }
        if (-not (Test-Path $catalogYaml)) { continue }
        $allSkills[$dir.Name] = Read-CatalogYaml $catalogYaml
    }

    $errorCount = 0
    $warnCount = 0
    $infoCount = 0

    # Severity constants and display config
    $SevError = "error"
    $SevWarn  = "warning"
    $SevInfo  = "info"
    $sevColors = @{ $SevError = "Red"; $SevWarn = "DarkYellow"; $SevInfo = "DarkGray" }
    $sevLabels = @{ $SevError = "[ERROR]"; $SevWarn = "[WARN] "; $SevInfo = "[INFO] " }

    foreach ($dir in (Get-ChildItem $LibraryDir -Directory | Sort-Object Name)) {
        $catalogYaml = Join-Path $dir.FullName "catalog.yaml"
        $skillMd = Join-Path $dir.FullName "SKILL.md"
        if (-not (Test-Path $skillMd)) { continue }

        $catalog = Read-CatalogYaml $catalogYaml
        $name = $dir.Name
        $skillIssues = @()

        # catalog.yaml exists (error)
        if (-not (Test-Path $catalogYaml)) {
            $skillIssues += @{ Severity = $SevError; Message = "missing catalog.yaml" }
        }

        # id_matches_dir (error)
        $id = $catalog["id"]
        if ($id -and $id -ne $name) {
            $skillIssues += @{ Severity = $SevError; Message = "catalog.yaml id '$id' does not match directory name '$name'" }
        }

        # scope_valid (error)
        $scope = $catalog["scope"]
        if (-not $scope) {
            $skillIssues += @{ Severity = $SevError; Message = "missing scope field" }
        } elseif ($scope -ne "general" -and $scope -ne "project") {
            $skillIssues += @{ Severity = $SevError; Message = "scope must be 'general' or 'project' (got '$scope')" }
        }

        # tags (warning)
        $tags = $catalog["tags"]
        if (-not $tags -or ($tags -is [string] -and $tags -eq "[]")) {
            $skillIssues += @{ Severity = $SevWarn; Message = "missing tags" }
        }

        # Extract description for length checks
        $content = Get-Content $skillMd -Raw
        $description = ""
        if ($content -match '(?ms)^---\s*\n(.*?)\n---') {
            $fm = $Matches[1]
            $fmLines = $fm -split "`n"
            for ($i = 0; $i -lt $fmLines.Count; $i++) {
                if ($fmLines[$i] -match '^description:\s*(.*)$') {
                    $val = $Matches[1].Trim()
                    if ($val -match '^[>|]-?\s*$') {
                        $parts = @()
                        for ($j = $i + 1; $j -lt $fmLines.Count; $j++) {
                            if ($fmLines[$j] -match '^\s+(.+)') { $parts += $Matches[1].Trim() } else { break }
                        }
                        $description = ($parts -join ' ').Trim()
                    } elseif ($val -match '^"(.+)"$') { $description = $Matches[1] }
                    else { $description = $val.Trim('"') }
                    break
                }
            }
        }
        # description_length (warning, lower + upper)
        if ($description.Length -lt 50) {
            $skillIssues += @{ Severity = $SevWarn; Message = "short description ($($description.Length) chars)" }
        } elseif ($description.Length -gt 500) {
            $skillIssues += @{ Severity = $SevWarn; Message = "long description ($($description.Length) chars, >500; Claude/Factory may truncate)" }
        }

        # targets_any (error) + single-target info
        $targets = $catalog["targets"]
        $activeTargets = @()
        if ($targets) {
            if ($targets["codex"]) { $activeTargets += "codex" }
            if ($targets["claude"]) { $activeTargets += "claude" }
            if ($targets["factory"]) { $activeTargets += "factory" }
            if ($targets["desktop"]) { $activeTargets += "desktop" }
        }
        if ($activeTargets.Count -eq 0) {
            $skillIssues += @{ Severity = $SevError; Message = "no targets enabled" }
        } elseif ($activeTargets.Count -eq 1 -and $scope -ne "project") {
            $skillIssues += @{ Severity = $SevInfo; Message = "single-target ($($activeTargets[0])) - consider cross-pollinating" }
        }

        # size_discipline_hard (error if >500 body lines)
        $bodyText = Get-SkillMdBody $skillMd
        $bodyLines = @($bodyText -split "`n").Count
        if ($bodyLines -gt 500) {
            $skillIssues += @{ Severity = $SevError; Message = "SKILL.md body is $bodyLines lines (>500); move detail to references/" }
        }

        # related_exists (error) + related_bidirectional (warning)
        $related = $catalog["related"]
        if ($related) {
            if ($related -isnot [array]) { $related = @($related) }
            foreach ($rid in $related) {
                if (-not $allSkills.ContainsKey($rid)) {
                    $skillIssues += @{ Severity = $SevError; Message = "related id '$rid' does not match any skill" }
                } else {
                    $otherCatalog = $allSkills[$rid]
                    $otherRelated = $otherCatalog["related"]
                    if ($otherRelated -and $otherRelated -isnot [array]) { $otherRelated = @($otherRelated) }
                    if (-not $otherRelated -or ($otherRelated -notcontains $name)) {
                        $skillIssues += @{ Severity = $SevWarn; Message = "'$rid' does not list '$name' in its related field" }
                    }
                }
            }
        }

        if ($skillIssues.Count -gt 0) {
            Write-Host "`n  $name" -ForegroundColor Yellow
            foreach ($issue in $skillIssues) {
                $sev = $issue.Severity
                $label = $sevLabels[$sev]
                $color = $sevColors[$sev]
                Write-Host "    - $label $($issue.Message)" -ForegroundColor $color
                if ($sev -eq $SevError) { $errorCount++ }
                elseif ($sev -eq $SevWarn) { $warnCount++ }
                else { $infoCount++ }
            }
        }
    }

    $total = $errorCount + $warnCount + $infoCount
    if ($total -eq 0) {
        Write-Host "`nNo issues found." -ForegroundColor Green
    } else {
        $summary = "$errorCount error(s), $warnCount warning(s), $infoCount info"
        if ($errorCount -gt 0) {
            Write-Host "`n$summary" -ForegroundColor Red
        } else {
            Write-Host "`n$summary" -ForegroundColor Yellow
        }
    }

    return $errorCount
}

# --- Main ---

Write-Host "Skill Library Sync" -ForegroundColor Cyan
Write-Host "Library: $LibraryDir" -ForegroundColor DarkGray

switch ($Command) {
    "push" {
        if ($Target -eq "all" -or $Target -eq "codex")   { Push-Codex }
        if ($Target -eq "all" -or $Target -eq "claude")   { Push-Claude }
        if ($Target -eq "all" -or $Target -eq "factory")  { Push-Factory }
        if ($Target -eq "all" -or $Target -eq "desktop")  { Push-Desktop }
        Update-CatalogJson
        Write-Host "`nPush complete." -ForegroundColor Green
    }
    "pull" {
        if ($Target -eq "all" -or $Target -eq "codex")   { Pull-Codex }
        if ($Target -eq "all" -or $Target -eq "claude")   { Pull-Claude }
        if ($Target -eq "all" -or $Target -eq "factory")  { Pull-Factory }
        Update-CatalogJson
        Write-Host "`nPull complete." -ForegroundColor Green
    }
    "status" {
        Show-Status
    }
    "diff" {
        if ($Target -eq "all" -or $Target -eq "codex")   { Diff-Codex }
        if ($Target -eq "all" -or $Target -eq "claude")   { Diff-Claude }
        if ($Target -eq "all" -or $Target -eq "factory")  { Diff-Factory }
        if ($Target -eq "all" -or $Target -eq "desktop")  { Diff-Desktop }
    }
    "search" {
        Search-Skills $Target
    }
    "lint" {
        $lintErrors = Invoke-Lint
        if ($lintErrors -gt 0) { exit 2 }
    }
}
